stages:
  - build
  - test
  - package
  - deploy
  - acceptancetest


build:
  stage: build
  image: openjdk:15
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./build/libs/helloworldaws.jar


test:
  stage: test
  image: openjdk:15
  script:
    - ./gradlew check --info

package:
   image: docker:latest
   services:
     - docker:dind
   stage: package
   script:
     - docker build -t steinko/helloworldaws .
     - docker login -u steinko -p RoxyMusic11
     - docker push steinko/helloworldaws


deploy:
   stage: deploy
   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
   script:
     - aws elasticbeanstalk  update-application --application-name HelloWorldDocker   --region eu-north-1

acceptancetest:
   stage: acceptancetest
   image: openjdk:15
   script:
     - cd apitest
     - ./gradlew cucumber --info