stages:
  - build
  - test
  - deploy
  - acceptancetest


build:
  stage: build
  image: openjdk:15
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./build/libs/HelloWorldAWS-0.0.1-SNAPSHOT.jar


test:
  stage: test
  image: openjdk:15
  script:
    - ./gradlew check

deploy:
   stage: deploy
   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
   script:
     - aws elasticbeanstalk  update-application --application-name HelloWorldAWS  --region eu-north-1 --aws_access_key_id "$AWS_ACCESS_KEY_ID"  --aws_secret_access_key  "$AWS_SECRET_ACCESS_KEY"

acceptancetest:
   stage: acceptancetest
   script:
     - cd apitest
     - ./gradlew cucumber --info