stages:
  - build
  - test
  - deploy


build:
  stage: build
  image: openjdk:15
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - ./build/libs/HelloWorldAWS-0.0.1-SNAPSHOT.jar


test:
  stage: test
  image: openjdk:15
  script:
    - ./gradlew check

deploy:
   stage: deploy
   image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
   script:
     - aws elasticbeanstalk  update-application--application-name HelloWorldAWS